### ISSUE TITLE
plpgsql implementation

### ISSUE THREAD

**Issue by benbro** [dverite/permuteseq#3]
Is there a plpgsql implementation?

Thanks

**Comment by dverite** [comment]
There's no plpgsql version, but patches for that would be welcome. The hard part consists of emulating uint64/uint32 in cycle_walking_cipher(), since plpgsql does not have unsigned types.

**Comment by benbro** [comment]
From my understanding, the code does several things:
1. Compute the half block size.
2. Loop until result is in the desired range - Cycle-Walking Cipher.
3. Compute the result with a Feistel network.

Step 2 is similar to the [constrained example](https://wiki.postgresql.org/wiki/Pseudo_encrypt_constrained_to_an_arbitrary_range) in the postgresql wiki.

If I'll be able to translate the Feistel network part to plpgsql I'll have all the parts?
There is a [Feistel network example](https://wiki.postgresql.org/wiki/Pseudo_encrypt) in the wiki but it's missing the crypto key.

Will [Skip32](https://github.com/dverite/pg-uniqrand/blob/master/skip32.sql) or [XTEA](https://github.com/dverite/pg-uniqrand/blob/master/xtea.sql) wrapped with Cycle-Walking Cipher give the same effect?

**Comment by dverite** [comment]
Yes, if the desired output space is close to 64-bit or 32-bit, then using respectively XTEA or skip32, wrapped in a cycle-walking loop, that would be perfect. But the problem is: when the output has to be much smaller (for ex. 1..10000),  the cycle-walking loop over these functions could iterate for an unpleasantly high number of times before hitting a value that happens to be in that range.

In fact, it's the main idea behind permuteseq: handling that problem by auto-adapting the block size to support smaller output spaces, and more generally, all output spaces up to 64-bit.

**Comment by benbro** [comment]
My desired output space is 1,000,000,000. On average it will require 5 loops when using 32-bit. Not sure if it's considered reasonable or not.

Is it possible to use XTEA with a custom block size inside the cycle-walking loop similar to your [example here](https://stackoverflow.com/questions/33760630/generate-unique-random-numbers-in-postgresql-with-fixed-length/33811338#33811338)?
Why aren't you using XTEA in the loop if you already have it implemented in C and plpgsql?

Is there an equivalent to hash_uint32 in plpgsql?

**Comment by dverite** [comment]
1 billion is close enough to 2^32 (in terms of the probability of a random value in the [-2^31..2^31] range to be also in [1..1e9]). So I think that a cycle-walking on top of skip32 would work fine.

As far as I understand, it is impossible to change XTEA's block size, otherwise permuteseq would use that method indeed.

There's no port of `hash_uint32` in plpgsql that I know of. But note that if you're not interested in being compatible with permuteseq output values, you could use whatever suits you in the round function. It just has to produce values that are as dispersed/random-looking as possible, and be a function in the mathematical sense, x=y => f(x)=f(y)

**Comment by benbro** [comment]
I don't have enough C and plpgsql knowledge to translate permuteseq.
I'll use cycle-walking on top of your plpgsql implementation of [skip32](https://github.com/dverite/pg-uniqrand/blob/master/skip32.sql) as you suggested.
Thank you for the help.
